use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use sha2::{Digest, Sha256};
use sqlx::sqlite::SqliteConnectOptions;
use sqlx::{Connection, Row, SqliteConnection};
use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};
use tauri::Manager;

use crate::app_paths;

/// env key 中出现这些子串即视为机密，值只返回掩码。
const SECRET_KEY_MARKERS: [&str; 5] = ["token", "key", "secret", "auth", "password"];
const CLI_MANAGER_CODEX_PROFILE_MARKER: &str = "Generated by CLI-Manager";
const PROVIDER_MODEL_TEST_TIMEOUT_SECS: u64 = 30;
const PROVIDER_MODEL_TEST_DEGRADED_THRESHOLD_MS: u64 = 6000;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchProvider {
    id: String,
    app_type: String,
    name: String,
    category: Option<String>,
    website_url: Option<String>,
    notes: Option<String>,
    sort_index: Option<i64>,
    created_at: Option<i64>,
    is_current: bool,
    base_url: Option<String>,
    model: Option<String>,
    api_format: Option<String>,
    masked_env: BTreeMap<String, String>,
    config_parse_error: bool,
    /// Raw settings_config JSON text (for display only, not for actual application)
    raw_settings_config: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchProvidersResponse {
    db_path: String,
    providers: Vec<CcSwitchProvider>,
}

#[derive(Serialize)]
#[serde(rename_all = "lowercase")]
pub enum CcSwitchModelTestStatus {
    Operational,
    Degraded,
    Failed,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchModelTestResult {
    status: CcSwitchModelTestStatus,
    success: bool,
    message: String,
    response_time_ms: Option<u64>,
    http_status: Option<u16>,
    tested_at: i64,
    retry_count: u32,
}

pub(crate) fn is_secret_env_key(key: &str) -> bool {
    let lower = key.to_lowercase();
    SECRET_KEY_MARKERS
        .iter()
        .any(|marker| lower.contains(marker))
}

pub(crate) fn mask_secret(value: &str) -> String {
    let chars: Vec<char> = value.chars().collect();
    if chars.len() > 12 {
        let head: String = chars[..4].iter().collect();
        let tail: String = chars[chars.len() - 4..].iter().collect();
        format!("{head}…{tail}")
    } else {
        "***".to_string()
    }
}

fn env_value_text(value: &Value) -> String {
    match value {
        Value::String(text) => text.clone(),
        other => other.to_string(),
    }
}

struct ParsedConfig {
    base_url: Option<String>,
    model: Option<String>,
    masked_env: BTreeMap<String, String>,
}

fn non_empty_text(value: String) -> Option<String> {
    let trimmed = value.trim();
    (!trimmed.is_empty()).then(|| trimmed.to_string())
}

fn parse_settings_config(raw: &str) -> Option<ParsedConfig> {
    let value: Value = serde_json::from_str(raw).ok()?;
    let mut parsed = ParsedConfig {
        base_url: None,
        model: None,
        masked_env: BTreeMap::new(),
    };
    for env_key in ["env", "auth"] {
        if let Some(env) = value.get(env_key).and_then(Value::as_object) {
            for (key, raw_value) in env {
                let text = env_value_text(raw_value);
                let normalized = normalize_config_key(key);

                // Generic pattern matching: *_BASE_URL / *_API_BASE / *_ENDPOINT
                if normalized.ends_with("_BASE_URL")
                    || normalized.ends_with("_API_BASE")
                    || normalized.ends_with("_ENDPOINT")
                {
                    parsed.base_url = Some(text.clone());
                }
                // Generic pattern matching: *_MODEL
                else if normalized.ends_with("_MODEL") {
                    parsed.model = Some(text.clone());
                }

                let display = if is_secret_env_key(key) {
                    mask_secret(&text)
                } else {
                    text
                };
                parsed.masked_env.insert(key.clone(), display);
            }
        }
    }
    if let Some(config) = value.get("config").and_then(Value::as_str) {
        parsed.base_url = parsed
            .base_url
            .or_else(|| find_codex_toml_provider_base_url(config));
        parsed.model = parsed
            .model
            .or_else(|| find_toml_value_by_key_patterns(config, &["model"], &["_MODEL"]));
    }
    Some(parsed)
}

fn parse_api_format(meta: &str) -> Option<String> {
    let value: Value = serde_json::from_str(meta).ok()?;
    value
        .get("apiFormat")
        .and_then(Value::as_str)
        .map(str::to_string)
}

pub(crate) fn resolve_db_path(
    app: &tauri::AppHandle,
    db_path: Option<String>,
) -> Result<PathBuf, String> {
    let custom = db_path
        .map(|p| p.trim().to_string())
        .filter(|p| !p.is_empty());
    let path = match custom {
        Some(custom) => PathBuf::from(custom),
        None => app
            .path()
            .home_dir()
            .map_err(|err| format!("home_dir_unavailable: {err}"))?
            .join(".cc-switch")
            .join("cc-switch.db"),
    };
    if path.extension().and_then(|ext| ext.to_str()) != Some("db") {
        return Err("unsupported_format".to_string());
    }
    if !path.is_file() {
        return Err("db_not_found".to_string());
    }
    Ok(path)
}

async fn open_db_readonly(path: &Path) -> Result<SqliteConnection, String> {
    let options = SqliteConnectOptions::new().filename(path).read_only(true);
    SqliteConnection::connect_with(&options)
        .await
        .map_err(|err| format!("db_open_failed: {err}"))
}

fn provider_from_row(row: &sqlx::sqlite::SqliteRow) -> Result<CcSwitchProvider, String> {
    let map_err = |err: sqlx::Error| format!("db_query_failed: {err}");
    let settings_config: String = row.try_get("settings_config").map_err(map_err)?;
    let meta: String = row.try_get("meta").map_err(map_err)?;

    let parsed = parse_settings_config(&settings_config);
    let config_parse_error = parsed.is_none();
    let parsed = parsed.unwrap_or(ParsedConfig {
        base_url: None,
        model: None,
        masked_env: BTreeMap::new(),
    });

    Ok(CcSwitchProvider {
        id: row.try_get("id").map_err(map_err)?,
        app_type: row.try_get("app_type").map_err(map_err)?,
        name: row.try_get("name").map_err(map_err)?,
        category: row.try_get("category").map_err(map_err)?,
        website_url: row.try_get("website_url").map_err(map_err)?,
        notes: row.try_get("notes").map_err(map_err)?,
        sort_index: row.try_get("sort_index").map_err(map_err)?,
        created_at: row.try_get("created_at").map_err(map_err)?,
        is_current: row.try_get("is_current").map_err(map_err)?,
        base_url: parsed.base_url,
        model: parsed.model,
        api_format: parse_api_format(&meta),
        masked_env: parsed.masked_env,
        config_parse_error,
        raw_settings_config: settings_config,
    })
}

#[tauri::command]
pub async fn ccswitch_list_providers(
    app: tauri::AppHandle,
    db_path: Option<String>,
) -> Result<CcSwitchProvidersResponse, String> {
    let path = resolve_db_path(&app, db_path)?;

    let mut conn = open_db_readonly(&path).await?;

    let rows = sqlx::query(
        "SELECT id, app_type, name, settings_config, website_url, category, notes, \
         sort_index, created_at, is_current, meta \
         FROM providers ORDER BY app_type, sort_index, name",
    )
    .fetch_all(&mut conn)
    .await
    .map_err(|err| format!("db_query_failed: {err}"))?;

    let providers = rows
        .iter()
        .map(provider_from_row)
        .collect::<Result<Vec<_>, _>>()?;

    let _ = conn.close().await;

    Ok(CcSwitchProvidersResponse {
        db_path: path.to_string_lossy().into_owned(),
        providers,
    })
}

fn compact_text(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn truncate_text(text: &str, max_chars: usize) -> String {
    let mut chars = text.chars();
    let short: String = chars.by_ref().take(max_chars).collect();
    if chars.next().is_some() {
        format!("{short}...")
    } else {
        short
    }
}

fn truncate_error_text(text: &str) -> String {
    truncate_text(text, 120)
}

fn json_string_at<'a>(value: &'a Value, path: &[&str]) -> Option<&'a str> {
    let mut current = value;
    for key in path {
        current = current.get(*key)?;
    }
    current.as_str()
}

/// 从常见聚合网关错误里提取“哪个模型没有可用渠道”。
///
/// 前置条件：`message` 是已经去掉 request id 的错误文本。
/// 后置结果：命中特定句式时返回简短摘要；未命中时返回 None 交给通用摘要逻辑处理。
/// 副作用：无，只做字符串解析。
fn model_channel_hint(message: &str) -> Option<String> {
    let phrase = "no available channel for model";
    let lower = message.to_ascii_lowercase();
    let start = lower.find(phrase)?;
    let rest = message[start + phrase.len()..].trim();
    let model = rest
        .split_whitespace()
        .take_while(|part| {
            let lower = part.to_ascii_lowercase();
            lower != "under" && lower != "undergroup"
        })
        .collect::<Vec<_>>()
        .join(" ");
    (!model.is_empty()).then(|| format!("No channel for model {model}"))
}

/// 移除错误体里的 request id，避免 tooltip 被一次性请求标识撑得很长。
///
/// 前置条件：输入是供应商原始错误体或已压缩文本。
/// 后置结果：删除包含 request id 的括号片段，并合并多余空白。
/// 副作用：无，不修改原始字符串。
fn remove_request_id(text: &str) -> String {
    let mut result = text.to_string();
    loop {
        let lower = result.to_ascii_lowercase();
        let Some(idx) = lower.find("request id") else {
            break;
        };
        let start = result[..idx].rfind('(').unwrap_or(idx);
        let end = result[idx..]
            .find(')')
            .map(|offset| idx + offset + 1)
            .unwrap_or(result.len());
        result.replace_range(start..end, "");
    }
    compact_text(&result)
}

/// 从“像 JSON 但不一定合法”的错误体里提取 key 后面的值。
///
/// 前置条件：`text` 可能是被网关包了一层引号、标点混乱或非标准 JSON 的错误体。
/// 后置结果：返回第一个匹配 key 的短值；找不到时返回 None。
/// 副作用：无；这是合法 JSON 解析失败后的兜底路径。
fn extract_jsonish_key(text: &str, keys: &[&str]) -> Option<String> {
    let lower = text.to_ascii_lowercase();
    for key in keys {
        let Some(idx) = lower.find(&key.to_ascii_lowercase()) else {
            continue;
        };
        let after = &text[idx + key.len()..];
        let trimmed = after.trim_start_matches(|ch: char| {
            ch.is_whitespace() || matches!(ch, '"' | '\'' | ':' | '.' | '=' | '{' | '[')
        });
        let value = if trimmed.starts_with('"') || trimmed.starts_with('\'') {
            let quote = trimmed.chars().next()?;
            let inner = &trimmed[quote.len_utf8()..];
            inner
                .find(quote)
                .map(|end| &inner[..end])
                .unwrap_or(inner)
        } else {
            trimmed
                .split([',', '}', ']'])
                .next()
                .unwrap_or(trimmed)
        };
        let value = compact_text(value.trim_matches(|ch: char| {
            ch.is_whitespace() || matches!(ch, '"' | '\'' | ':' | '.' | '=' | '(' | ')')
        }));
        if !value.is_empty() {
            return Some(value);
        }
    }
    None
}

/// 把供应商返回的冗长错误体压缩成适合 tooltip/toast 的摘要。
///
/// 前置条件：`status` 是真实模型请求返回的 HTTP 状态码，`body` 是原始响应体。
/// 后置结果：优先返回 `code - message` 这类可读摘要，并去掉 request id、长 JSON 包装和堆栈噪音。
/// 副作用：无；这里不记录原文，避免把密钥或过长请求标识带到前端提示里。
fn summarize_model_error(status: u16, body: &str) -> String {
    let cleaned = remove_request_id(&body.replace("\\\"", "\""));
    let from_json = serde_json::from_str::<Value>(&cleaned).ok().and_then(|value| {
        let code = json_string_at(&value, &["error", "code"])
            .or_else(|| json_string_at(&value, &["error", "type"]))
            .or_else(|| json_string_at(&value, &["code"]))
            .or_else(|| json_string_at(&value, &["type"]));
        let message = json_string_at(&value, &["error", "message"])
            .or_else(|| json_string_at(&value, &["message"]))
            .or_else(|| json_string_at(&value, &["msg"]))
            .or_else(|| json_string_at(&value, &["detail"]));
        match (code, message) {
            (Some(code), Some(message)) if code != message => {
                Some(format!("{code} - {}", model_channel_hint(message).unwrap_or_else(|| message.to_string())))
            }
            (_, Some(message)) => Some(model_channel_hint(message).unwrap_or_else(|| message.to_string())),
            (Some(code), None) => Some(code.to_string()),
            _ => None,
        }
    });
    let summary = from_json.or_else(|| {
        let code = extract_jsonish_key(&cleaned, &["code", "type"]);
        let message = extract_jsonish_key(&cleaned, &["message", "mesage", "msg", "detail"]);
        match (code, message) {
            (Some(code), Some(message)) if code != message => {
                Some(format!("{code} - {}", model_channel_hint(&message).unwrap_or(message)))
            }
            (_, Some(message)) => Some(model_channel_hint(&message).unwrap_or(message)),
            (Some(code), None) => Some(code),
            _ => model_channel_hint(&cleaned).or_else(|| (!cleaned.is_empty()).then_some(cleaned)),
        }
    });
    match summary {
        Some(summary) => format!("HTTP {status}: {}", truncate_error_text(&summary)),
        None => format!("HTTP {status}"),
    }
}

fn endpoint_url(base_url: &str, versioned_path: &str) -> String {
    let base = base_url.trim().trim_end_matches('/');
    let path = versioned_path.trim().trim_start_matches('/');
    if base.ends_with(&format!("/{path}")) {
        return base.to_string();
    }
    if let Some(rest) = path.strip_prefix("v1/") {
        if base.ends_with("/v1") {
            return format!("{base}/{rest}");
        }
    }
    format!("{base}/{path}")
}

/// 包装模型测试结果。
///
/// 前置条件：调用方已经完成真实模型请求并传入 HTTP 状态码、响应体摘要与耗时。
/// 后置结果：只有 2xx HTTP 响应才算模型可用；401/403/404/5xx 等都会归类为失败。
/// 副作用：无，只构造可序列化结果。
fn build_model_test_result(
    result: Result<(u16, String), String>,
    response_time_ms: u64,
) -> CcSwitchModelTestResult {
    let tested_at = chrono::Utc::now().timestamp();
    match result {
        Ok((status, _body)) if (200..300).contains(&status) => CcSwitchModelTestResult {
            status: if response_time_ms <= PROVIDER_MODEL_TEST_DEGRADED_THRESHOLD_MS {
                CcSwitchModelTestStatus::Operational
            } else {
                CcSwitchModelTestStatus::Degraded
            },
            success: true,
            message: "Model test passed".to_string(),
            response_time_ms: Some(response_time_ms),
            http_status: Some(status),
            tested_at,
            retry_count: 0,
        },
        Ok((status, body)) => CcSwitchModelTestResult {
            status: CcSwitchModelTestStatus::Failed,
            success: false,
            message: summarize_model_error(status, &body),
            response_time_ms: Some(response_time_ms),
            http_status: Some(status),
            tested_at,
            retry_count: 0,
        },
        Err(message) => CcSwitchModelTestResult {
            status: CcSwitchModelTestStatus::Failed,
            success: false,
            message,
            response_time_ms: Some(response_time_ms),
            http_status: None,
            tested_at,
            retry_count: 0,
        },
    }
}

fn map_model_test_error(err: reqwest::Error) -> String {
    if err.is_timeout() {
        "Request timeout".to_string()
    } else if err.is_connect() {
        format!("Connection failed: {err}")
    } else {
        err.to_string()
    }
}

/// 从 cc-switch 的 Claude 供应商配置里提取真实模型请求所需三要素。
///
/// 前置条件：`settings_config` 是 providers.settings_config 中的 JSON 文本。
/// 后置结果：返回 base_url、鉴权 token、模型名；任一缺失都返回明确错误码。
/// 副作用：无；这里只做解析，不触网、不读取数据库。
fn claude_model_test_config(settings_config: &str) -> Result<(String, String, String), String> {
    let parsed: Value = serde_json::from_str(settings_config)
        .map_err(|_| "provider_config_invalid".to_string())?;
    let env = env_object(&parsed);
    let base_url = env
        .and_then(|env| env_text(env, "ANTHROPIC_BASE_URL").and_then(non_empty_text))
        .or_else(|| {
            find_text_by_key_patterns(
                &parsed,
                &["ANTHROPIC_BASE_URL", "base_url", "api_base", "endpoint", "url"],
                &["_BASE_URL", "_API_BASE", "_ENDPOINT"],
            )
            .and_then(non_empty_text)
        })
        .ok_or_else(|| "provider_config_invalid: missing_claude_base_url".to_string())?;
    let token = env
        .and_then(|env| env_text(env, "ANTHROPIC_API_KEY").and_then(non_empty_text))
        .or_else(|| env.and_then(|env| env_text(env, "ANTHROPIC_AUTH_TOKEN").and_then(non_empty_text)))
        .or_else(|| {
            find_text_by_key_patterns(
                &parsed,
                &["ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN", "api_key", "auth_token"],
                &["_API_KEY", "_AUTH_TOKEN", "_ACCESS_TOKEN", "_TOKEN"],
            )
            .and_then(non_empty_text)
        })
        .ok_or_else(|| "provider_config_invalid: missing_claude_api_key".to_string())?;
    let model = env
        .and_then(|env| env_text(env, "ANTHROPIC_MODEL").and_then(non_empty_text))
        .or_else(|| env.and_then(|env| env_text(env, "ANTHROPIC_SMALL_FAST_MODEL").and_then(non_empty_text)))
        .or_else(|| {
            find_text_by_key_patterns(
                &parsed,
                &["ANTHROPIC_MODEL", "ANTHROPIC_SMALL_FAST_MODEL", "model"],
                &["_MODEL"],
            )
            .and_then(non_empty_text)
        })
        .ok_or_else(|| "provider_config_invalid: missing_claude_model".to_string())?;
    Ok((base_url, token, model))
}

/// 发起 Claude Messages API 的最小模型请求。
///
/// 前置条件：base_url、token、model 已通过配置解析且非空。
/// 后置结果：返回 HTTP 状态码和响应体，由调用方统一判断 2xx/失败。
/// 副作用：会消耗一次极小的模型请求；同时发送 x-api-key 与 Bearer 是为了兼容不同代理网关。
async fn post_claude_model_test(
    client: &reqwest::Client,
    base_url: &str,
    token: &str,
    model: &str,
) -> Result<(u16, String), String> {
    let url = endpoint_url(base_url, "v1/messages");
    let resp = client
        .post(url)
        .timeout(Duration::from_secs(PROVIDER_MODEL_TEST_TIMEOUT_SECS))
        .header("content-type", "application/json")
        .header("anthropic-version", "2023-06-01")
        .header("x-api-key", token)
        .header("authorization", format!("Bearer {token}"))
        .json(&serde_json::json!({
            "model": model,
            "max_tokens": 1,
            "messages": [{ "role": "user", "content": "ping" }]
        }))
        .send()
        .await
        .map_err(map_model_test_error)?;
    let status = resp.status().as_u16();
    let body = resp.text().await.unwrap_or_default();
    Ok((status, body))
}

/// 发起 Codex/OpenAI 兼容接口的最小模型请求。
///
/// 前置条件：base_url、token、model 已通过配置解析且非空，wire_api 可为空。
/// 后置结果：按 wire_api 选择 Responses 或 Chat Completions 端点，并返回原始 HTTP 结果。
/// 副作用：会消耗一次极小的模型请求；不做端点自动降级，避免把模型错误误判成协议 fallback。
async fn post_codex_model_test(
    client: &reqwest::Client,
    base_url: &str,
    token: &str,
    model: &str,
    wire_api: Option<&str>,
) -> Result<(u16, String), String> {
    let is_chat = wire_api
        .map(|value| value.to_ascii_lowercase())
        .is_some_and(|value| value.contains("chat"));
    let (url, body) = if is_chat {
        (
            endpoint_url(base_url, "v1/chat/completions"),
            serde_json::json!({
                "model": model,
                "messages": [{ "role": "user", "content": "ping" }],
                "max_tokens": 1,
                "stream": false
            }),
        )
    } else {
        (
            endpoint_url(base_url, "v1/responses"),
            serde_json::json!({
                "model": model,
                "input": "ping",
                "max_output_tokens": 1,
                "store": false
            }),
        )
    };
    let resp = client
        .post(url)
        .timeout(Duration::from_secs(PROVIDER_MODEL_TEST_TIMEOUT_SECS))
        .header("content-type", "application/json")
        .header("authorization", format!("Bearer {token}"))
        .json(&body)
        .send()
        .await
        .map_err(map_model_test_error)?;
    let status = resp.status().as_u16();
    let body = resp.text().await.unwrap_or_default();
    Ok((status, body))
}

/// 测试 cc-switch 供应商配置里的真实模型请求。
///
/// 前置条件：`provider_id` 必须存在于 cc-switch.db，且配置中能解析出 base_url、密钥与模型。
/// 后置结果：只有真实模型接口返回 2xx 才算正常；鉴权、模型、路径、限流错误都会显示失败。
/// 副作用：会发起一次最小模型请求，可能产生极少量 token 消耗；不写数据库、不改项目供应商覆盖。
#[tauri::command]
pub async fn ccswitch_test_provider_model(
    app: tauri::AppHandle,
    db_path: Option<String>,
    app_type: String,
    provider_id: String,
) -> Result<CcSwitchModelTestResult, String> {
    let app_type = app_type.trim().to_ascii_lowercase();
    let provider_id = provider_id.trim();
    let path = resolve_db_path(&app, db_path)?;
    let mut conn = open_db_readonly(&path).await?;
    let row = sqlx::query(
        "SELECT name, settings_config FROM providers WHERE id = ?1 AND app_type = ?2",
    )
    .bind(provider_id)
    .bind(&app_type)
    .fetch_optional(&mut conn)
    .await
    .map_err(|err| format!("db_query_failed: {err}"))?;
    let _ = conn.close().await;
    let row = row.ok_or_else(|| "provider_not_found".to_string())?;
    let name: String = row
        .try_get("name")
        .map_err(|err| format!("db_query_failed: {err}"))?;
    let settings_config: String = row
        .try_get("settings_config")
        .map_err(|err| format!("db_query_failed: {err}"))?;

    let client = reqwest::Client::new();
    let start = Instant::now();
    let result = match app_type.as_str() {
        "claude" => {
            let (base_url, token, model) = claude_model_test_config(&settings_config)?;
            post_claude_model_test(&client, &base_url, &token, &model).await
        }
        "codex" => {
            let runtime =
                codex_runtime_from_provider(provider_id.to_string(), name, settings_config)?;
            let model = runtime
                .model
                .as_deref()
                .ok_or_else(|| "provider_config_invalid: missing_codex_model".to_string())?;
            post_codex_model_test(
                &client,
                &runtime.base_url,
                &runtime.secret_value,
                model,
                runtime.wire_api.as_deref(),
            )
            .await
        }
        _ => return Err("unsupported_app_type".to_string()),
    };
    let response_time_ms = start.elapsed().as_millis() as u64;

    Ok(build_model_test_result(result, response_time_ms))
}

// ---------- Phase 2：按项目切换供应商 ----------

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchProjectProvider {
    matched_provider_id: Option<String>,
    has_settings_file: bool,
    base_url: Option<String>,
    /// settings.local.json env 中 ANTHROPIC_ 前缀的 key 名（只含 key 名，不含值）。
    local_override_keys: Vec<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchCodexProviderProfile {
    provider_id: String,
    provider_name: String,
    profile_name: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchClaudeProviderSettings {
    provider_id: String,
    provider_name: String,
    settings_path: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexProviderLaunchConfig {
    pub provider_id: String,
    pub db_path: Option<String>,
    pub codex_config_dir: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClaudeProviderLaunchConfig {
    pub project_id: String,
    pub provider_id: String,
    pub db_path: Option<String>,
}

struct CodexProviderRuntimeConfig {
    provider_id: String,
    provider_name: String,
    profile_name: String,
    env_key: String,
    secret_value: String,
    base_url: String,
    model: Option<String>,
    wire_api: Option<String>,
    profile_text: String,
}

fn env_object(value: &Value) -> Option<&Map<String, Value>> {
    value.get("env").and_then(Value::as_object)
}

fn env_text(env: &Map<String, Value>, key: &str) -> Option<String> {
    env.get(key).map(env_value_text)
}

/// 纯函数：从 settings.local.json 文本提取 env 中 `ANTHROPIC_` 前缀的 key 名。
/// 只返回 key 名（不含值，避免泄密）；损坏 JSON / 顶层非对象 / 无 env → 空数组。
pub(crate) fn anthropic_env_keys(raw: &str) -> Vec<String> {
    let parsed: Option<Value> = serde_json::from_str(raw).ok();
    parsed
        .as_ref()
        .and_then(env_object)
        .map(|env| {
            env.keys()
                .filter(|key| key.starts_with("ANTHROPIC_"))
                .cloned()
                .collect()
        })
        .unwrap_or_default()
}

/// 项目 settings.json 的 env 与 provider env 匹配规则：
/// ANTHROPIC_BASE_URL 相等，且 ANTHROPIC_AUTH_TOKEN 或 ANTHROPIC_API_KEY 相等。
pub(crate) fn provider_matches_project_env(
    project_env: &Map<String, Value>,
    provider_env: &Map<String, Value>,
) -> bool {
    let same = |key: &str| match (env_text(project_env, key), env_text(provider_env, key)) {
        (Some(a), Some(b)) => a == b,
        _ => false,
    };
    same("ANTHROPIC_BASE_URL") && (same("ANTHROPIC_AUTH_TOKEN") || same("ANTHROPIC_API_KEY"))
}

/// env 替换规则：先移除现有 env 中所有 `ANTHROPIC_` 前缀 key（清掉上一家供应商遗留），
/// 再把 provider env 全量覆盖写入；env 之外的顶层字段保持原样。
/// 现有 env 缺失或不是对象时按空对象处理。
pub(crate) fn replace_anthropic_env(
    settings: &mut Map<String, Value>,
    provider_env: &Map<String, Value>,
) {
    let env_entry = settings
        .entry("env".to_string())
        .or_insert_with(|| Value::Object(Map::new()));
    if !env_entry.is_object() {
        *env_entry = Value::Object(Map::new());
    }
    let env = env_entry.as_object_mut().expect("env entry is an object");
    env.retain(|key, _| !key.starts_with("ANTHROPIC_"));
    for (key, value) in provider_env {
        env.insert(key.clone(), value.clone());
    }
}

/// 纯函数：输入现有 settings.json 文本（None 表示文件不存在）与 provider env，
/// 返回写盘用的新文本。损坏 JSON / 顶层非对象 → `settings_parse_failed`。
pub(crate) fn merge_settings_text(
    existing: Option<&str>,
    provider_env: &Map<String, Value>,
) -> Result<String, String> {
    let mut settings: Value = match existing {
        Some(raw) => serde_json::from_str(raw).map_err(|_| "settings_parse_failed".to_string())?,
        None => Value::Object(Map::new()),
    };
    let settings_obj = settings
        .as_object_mut()
        .ok_or_else(|| "settings_parse_failed".to_string())?;
    replace_anthropic_env(settings_obj, provider_env);
    let mut text = serde_json::to_string_pretty(&settings)
        .map_err(|err| format!("settings_write_failed: {err}"))?;
    text.push('\n');
    Ok(text)
}

async fn load_claude_provider_env(
    app: &tauri::AppHandle,
    provider_id: &str,
    db_path: Option<String>,
) -> Result<(String, Map<String, Value>), String> {
    let path = resolve_db_path(app, db_path)?;
    let mut conn = open_db_readonly(&path).await?;
    let row = sqlx::query(
        "SELECT name, settings_config FROM providers WHERE id = ?1 AND app_type = 'claude'",
    )
    .bind(provider_id.trim())
    .fetch_optional(&mut conn)
    .await
    .map_err(|err| format!("db_query_failed: {err}"))?;
    let _ = conn.close().await;

    let row = row.ok_or_else(|| "provider_not_found".to_string())?;
    let name: String = row
        .try_get("name")
        .map_err(|err| format!("db_query_failed: {err}"))?;
    let settings_config: String = row
        .try_get("settings_config")
        .map_err(|err| format!("db_query_failed: {err}"))?;
    let parsed: Option<Value> = serde_json::from_str(&settings_config).ok();
    let provider_env = parsed
        .as_ref()
        .and_then(env_object)
        .cloned()
        .ok_or_else(|| "provider_config_invalid".to_string())?;
    Ok((name, provider_env))
}

fn claude_settings_file_name(project_id: &str, provider_id: &str) -> String {
    format!(
        "{}-{}.settings.json",
        sanitize_codex_profile_slug(project_id),
        short_sha256(provider_id, 10)
    )
}

fn write_claude_provider_settings(
    project_id: &str,
    provider_id: &str,
    provider_env: &Map<String, Value>,
) -> Result<PathBuf, String> {
    let dir = app_paths::claude_providers_dir()?;
    fs::create_dir_all(&dir).map_err(|err| format!("settings_write_failed: {err}"))?;
    let settings_path = dir.join(claude_settings_file_name(project_id, provider_id));
    let text = merge_settings_text(None, provider_env)?;
    let tmp_path = settings_path.with_extension("json.tmp");
    fs::write(&tmp_path, text).map_err(|err| format!("settings_write_failed: {err}"))?;
    replace_file_with_tmp(&tmp_path, &settings_path, "settings_write_failed")?;
    Ok(settings_path)
}

#[tauri::command]
pub async fn ccswitch_get_project_provider(
    app: tauri::AppHandle,
    project_path: String,
    db_path: Option<String>,
) -> Result<CcSwitchProjectProvider, String> {
    let project_dir = PathBuf::from(project_path.trim());
    if !project_dir.is_dir() {
        return Err("project_not_found".to_string());
    }
    let settings_path = project_dir.join(".claude").join("settings.json");
    let has_settings_file = settings_path.is_file();

    // 读取失败/损坏 JSON 不报错：视为无 env，可由后续切换覆盖修复。
    let parsed_settings: Option<Value> = if has_settings_file {
        fs::read_to_string(&settings_path)
            .ok()
            .and_then(|raw| serde_json::from_str(&raw).ok())
    } else {
        None
    };
    let project_env: Map<String, Value> = parsed_settings
        .as_ref()
        .and_then(env_object)
        .cloned()
        .unwrap_or_default();
    let base_url = env_text(&project_env, "ANTHROPIC_BASE_URL");

    // settings.local.json 优先级高于 settings.json，提取其中 ANTHROPIC_ key 名用于前端冲突提示。
    // 文件不存在/损坏 → 空数组，容错不报错。
    let local_settings_path = project_dir.join(".claude").join("settings.local.json");
    let local_override_keys = fs::read_to_string(&local_settings_path)
        .map(|raw| anthropic_env_keys(&raw))
        .unwrap_or_default();

    let mut matched_provider_id = None;
    if !project_env.is_empty() {
        let path = resolve_db_path(&app, db_path)?;
        let mut conn = open_db_readonly(&path).await?;
        let rows = sqlx::query(
            "SELECT id, settings_config FROM providers \
             WHERE app_type = 'claude' ORDER BY sort_index, name",
        )
        .fetch_all(&mut conn)
        .await
        .map_err(|err| format!("db_query_failed: {err}"))?;
        let _ = conn.close().await;

        for row in &rows {
            let map_err = |err: sqlx::Error| format!("db_query_failed: {err}");
            let id: String = row.try_get("id").map_err(map_err)?;
            let settings_config: String = row.try_get("settings_config").map_err(map_err)?;
            let parsed: Option<Value> = serde_json::from_str(&settings_config).ok();
            let Some(provider_env) = parsed.as_ref().and_then(env_object) else {
                continue;
            };
            if provider_matches_project_env(&project_env, provider_env) {
                matched_provider_id = Some(id);
                break;
            }
        }
    }

    Ok(CcSwitchProjectProvider {
        matched_provider_id,
        has_settings_file,
        base_url,
        local_override_keys,
    })
}

#[tauri::command]
pub async fn ccswitch_apply_provider(
    app: tauri::AppHandle,
    project_path: String,
    provider_id: String,
    db_path: Option<String>,
) -> Result<(), String> {
    let project_dir = PathBuf::from(project_path.trim());
    if !project_dir.is_dir() {
        return Err("project_not_found".to_string());
    }

    let path = resolve_db_path(&app, db_path)?;
    let mut conn = open_db_readonly(&path).await?;
    let row =
        sqlx::query("SELECT settings_config FROM providers WHERE id = ?1 AND app_type = 'claude'")
            .bind(provider_id.trim())
            .fetch_optional(&mut conn)
            .await
            .map_err(|err| format!("db_query_failed: {err}"))?;
    let _ = conn.close().await;

    let row = row.ok_or_else(|| "provider_not_found".to_string())?;
    let settings_config: String = row
        .try_get("settings_config")
        .map_err(|err| format!("db_query_failed: {err}"))?;
    let parsed: Option<Value> = serde_json::from_str(&settings_config).ok();
    let provider_env = parsed
        .as_ref()
        .and_then(env_object)
        .ok_or_else(|| "provider_config_invalid".to_string())?;

    let claude_dir = project_dir.join(".claude");
    let settings_path = claude_dir.join("settings.json");
    let existing = if settings_path.is_file() {
        Some(
            fs::read_to_string(&settings_path)
                .map_err(|err| format!("settings_read_failed: {err}"))?,
        )
    } else {
        None
    };
    let next_text = merge_settings_text(existing.as_deref(), provider_env)?;
    atomic_write_settings(&claude_dir, &settings_path, &next_text)
}

#[tauri::command]
pub async fn ccswitch_prepare_claude_provider(
    app: tauri::AppHandle,
    project_id: String,
    provider_id: String,
    db_path: Option<String>,
) -> Result<CcSwitchClaudeProviderSettings, String> {
    let project_id = project_id.trim();
    if project_id.is_empty() {
        return Err("project_not_found".to_string());
    }
    let provider_id = provider_id.trim();
    let (provider_name, provider_env) =
        load_claude_provider_env(&app, provider_id, db_path).await?;
    let settings_path = write_claude_provider_settings(project_id, provider_id, &provider_env)?;
    Ok(CcSwitchClaudeProviderSettings {
        provider_id: provider_id.to_string(),
        provider_name,
        settings_path: settings_path.to_string_lossy().into_owned(),
    })
}

/// 原子写：同目录临时文件 + rename 覆盖，避免写一半留下损坏文件。
fn atomic_write_settings(
    claude_dir: &Path,
    settings_path: &Path,
    text: &str,
) -> Result<(), String> {
    fs::create_dir_all(claude_dir).map_err(|err| format!("settings_write_failed: {err}"))?;
    let tmp_path = claude_dir.join("settings.json.tmp");
    fs::write(&tmp_path, text).map_err(|err| format!("settings_write_failed: {err}"))?;
    replace_file_with_tmp(&tmp_path, settings_path, "settings_write_failed")
}

// ---------- Phase 3：恢复全局 + 项目树徽标 ----------

/// 纯函数：删除 settings.json 文本中顶层 `env` 字段（整段删除）。
/// 返回 `Ok(None)` 表示删除后顶层为空对象，调用方应删除文件本身；
/// `Ok(Some(text))` 为应原子写回的新文本。
/// 损坏 JSON / 顶层非对象 → `settings_parse_failed`。
pub(crate) fn strip_env_section(existing: &str) -> Result<Option<String>, String> {
    let mut settings: Value =
        serde_json::from_str(existing).map_err(|_| "settings_parse_failed".to_string())?;
    let settings_obj = settings
        .as_object_mut()
        .ok_or_else(|| "settings_parse_failed".to_string())?;
    settings_obj.remove("env");
    if settings_obj.is_empty() {
        return Ok(None);
    }
    let mut text = serde_json::to_string_pretty(&settings)
        .map_err(|err| format!("settings_write_failed: {err}"))?;
    text.push('\n');
    Ok(Some(text))
}

/// 恢复全局的文件操作部分（project_dir 已校验存在）：
/// settings.json 不存在 → no-op 成功；删 env 后为空 `{}` → 删除文件（`.claude/` 目录保留）。
fn reset_settings_file(project_dir: &Path) -> Result<(), String> {
    let claude_dir = project_dir.join(".claude");
    let settings_path = claude_dir.join("settings.json");
    if !settings_path.is_file() {
        return Ok(());
    }
    let existing =
        fs::read_to_string(&settings_path).map_err(|err| format!("settings_read_failed: {err}"))?;
    match strip_env_section(&existing)? {
        None => {
            fs::remove_file(&settings_path).map_err(|err| format!("settings_write_failed: {err}"))
        }
        Some(next_text) => atomic_write_settings(&claude_dir, &settings_path, &next_text),
    }
}

#[tauri::command]
pub async fn ccswitch_reset_project_provider(project_path: String) -> Result<(), String> {
    let project_dir = PathBuf::from(project_path.trim());
    if !project_dir.is_dir() {
        return Err("project_not_found".to_string());
    }
    reset_settings_file(&project_dir)
}

// ---------- Phase 3b：Codex profile adapter ----------

fn short_sha256(input: &str, len: usize) -> String {
    let digest = Sha256::digest(input.as_bytes());
    let full = format!("{digest:x}");
    full.chars().take(len).collect()
}

fn sanitize_codex_profile_slug(provider_id: &str) -> String {
    let mut slug = String::new();
    let mut last_dash = false;
    for ch in provider_id.chars() {
        let next = if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            ch.to_ascii_lowercase()
        } else {
            '-'
        };
        if next == '-' {
            if last_dash {
                continue;
            }
            last_dash = true;
        } else {
            last_dash = false;
        }
        slug.push(next);
    }
    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "provider".to_string()
    } else {
        slug.chars().take(40).collect()
    }
}

pub(crate) fn codex_profile_name(provider_id: &str) -> String {
    format!(
        "cli-manager-{}-{}",
        sanitize_codex_profile_slug(provider_id),
        short_sha256(provider_id, 10)
    )
}

fn codex_secret_env_key(provider_id: &str) -> String {
    format!(
        "CLI_MANAGER_CODEX_PROVIDER_{}_API_KEY",
        short_sha256(provider_id, 16).to_ascii_uppercase()
    )
}

fn toml_basic_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            c if c.is_control() => escaped.push_str(&format!("\\u{:04X}", c as u32)),
            c => escaped.push(c),
        }
    }
    escaped.push('"');
    escaped
}

fn find_env_by_exact_or_suffix(
    env: &Map<String, Value>,
    exact: &[&str],
    suffixes: &[&str],
) -> Option<String> {
    for key in exact {
        if let Some(value) = env_text(env, key) {
            if !value.trim().is_empty() {
                return Some(value);
            }
        }
    }
    env.iter().find_map(|(key, value)| {
        let upper = key.to_ascii_uppercase();
        if suffixes.iter().any(|suffix| upper.ends_with(suffix)) {
            let text = env_value_text(value);
            if !text.trim().is_empty() {
                return Some(text);
            }
        }
        None
    })
}

fn value_text_if_scalar(value: &Value) -> Option<String> {
    match value {
        Value::String(text) if !text.trim().is_empty() => Some(text.clone()),
        Value::Number(_) | Value::Bool(_) => {
            let text = env_value_text(value);
            (!text.trim().is_empty()).then_some(text)
        }
        _ => None,
    }
}

fn normalize_config_key(key: &str) -> String {
    key.replace(['-', '.'], "_").to_ascii_uppercase()
}

fn find_text_by_key_patterns(value: &Value, exact: &[&str], suffixes: &[&str]) -> Option<String> {
    match value {
        Value::Object(map) => {
            for (key, child) in map {
                let normalized = normalize_config_key(key);
                let exact_match = exact
                    .iter()
                    .any(|candidate| normalized == normalize_config_key(candidate));
                if exact_match || suffixes.iter().any(|suffix| normalized.ends_with(suffix)) {
                    if let Some(text) = value_text_if_scalar(child) {
                        return Some(text);
                    }
                }
            }
            map.values()
                .find_map(|child| find_text_by_key_patterns(child, exact, suffixes))
        }
        Value::Array(items) => items
            .iter()
            .find_map(|child| find_text_by_key_patterns(child, exact, suffixes)),
        _ => None,
    }
}

fn strip_toml_inline_comment(value: &str) -> &str {
    let mut in_string = false;
    let mut escaped = false;
    for (index, ch) in value.char_indices() {
        match ch {
            '\\' if in_string => escaped = !escaped,
            '"' if !escaped => in_string = !in_string,
            '#' if !in_string => return &value[..index],
            _ => escaped = false,
        }
    }
    value
}

fn parse_toml_scalar(value: &str) -> Option<String> {
    let value = strip_toml_inline_comment(value).trim();
    if value.is_empty() {
        return None;
    }
    if let Some(inner) = value.strip_prefix('"').and_then(|v| v.strip_suffix('"')) {
        let mut output = String::new();
        let mut chars = inner.chars();
        while let Some(ch) = chars.next() {
            if ch == '\\' {
                match chars.next() {
                    Some('n') => output.push('\n'),
                    Some('r') => output.push('\r'),
                    Some('t') => output.push('\t'),
                    Some('"') => output.push('"'),
                    Some('\\') => output.push('\\'),
                    Some(other) => output.push(other),
                    None => output.push('\\'),
                }
            } else {
                output.push(ch);
            }
        }
        return (!output.trim().is_empty()).then_some(output);
    }
    if let Some(inner) = value.strip_prefix('\'').and_then(|v| v.strip_suffix('\'')) {
        return (!inner.trim().is_empty()).then_some(inner.to_string());
    }
    (!value.trim().is_empty()).then_some(value.to_string())
}

fn toml_table_name(line: &str) -> Option<String> {
    let trimmed = line.trim();
    if trimmed.starts_with("[[") || !trimmed.starts_with('[') || !trimmed.ends_with(']') {
        return None;
    }
    Some(
        trimmed
            .trim_start_matches('[')
            .trim_end_matches(']')
            .trim()
            .to_string(),
    )
}

fn toml_assignment(line: &str) -> Option<(String, String)> {
    let trimmed = line.trim();
    if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with('[') {
        return None;
    }
    let (key, value) = trimmed.split_once('=')?;
    Some((
        key.trim().trim_matches('"').trim_matches('\'').to_string(),
        value.trim().to_string(),
    ))
}

fn find_toml_value_by_key_patterns(raw: &str, exact: &[&str], suffixes: &[&str]) -> Option<String> {
    for line in raw.lines() {
        let Some((key, value)) = toml_assignment(line) else {
            continue;
        };
        let normalized = normalize_config_key(&key);
        let exact_match = exact
            .iter()
            .any(|candidate| normalized == normalize_config_key(candidate));
        if exact_match || suffixes.iter().any(|suffix| normalized.ends_with(suffix)) {
            if let Some(text) = parse_toml_scalar(&value) {
                return Some(text);
            }
        }
    }
    None
}

fn find_codex_toml_provider_base_url(raw: &str) -> Option<String> {
    let selected_provider = find_toml_value_by_key_patterns(raw, &["model_provider"], &[]);
    let mut current_table: Option<String> = None;
    let mut fallback_base_url: Option<String> = None;
    for line in raw.lines() {
        if let Some(table) = toml_table_name(line) {
            current_table = Some(table);
            continue;
        }
        let Some((key, value)) = toml_assignment(line) else {
            continue;
        };
        if normalize_config_key(&key) != "BASE_URL" {
            continue;
        }
        let table = current_table.as_deref().unwrap_or_default();
        if !table.starts_with("model_providers.") {
            continue;
        }
        let Some(base_url) = parse_toml_scalar(&value) else {
            continue;
        };
        if selected_provider.as_deref().is_some_and(|provider| {
            table
                .trim_start_matches("model_providers.")
                .trim_matches('"')
                == provider
        }) {
            return Some(base_url);
        }
        fallback_base_url.get_or_insert(base_url);
    }
    fallback_base_url
}

fn find_codex_secret_value_in_value(value: &Value) -> Option<String> {
    const EXACT: [&str; 6] = [
        "OPENAI_API_KEY",
        "OPENAI_AUTH_TOKEN",
        "CODEX_API_KEY",
        "CODEX_AUTH_TOKEN",
        "API_KEY",
        "AUTH_TOKEN",
    ];
    find_text_by_key_patterns(
        value,
        &EXACT,
        &["_API_KEY", "_AUTH_TOKEN", "_ACCESS_TOKEN", "_TOKEN"],
    )
}

fn find_codex_secret_value(env: &Map<String, Value>) -> Option<String> {
    find_codex_secret_value_in_value(&Value::Object(env.clone()))
}

fn build_codex_profile_text(
    provider_name: &str,
    provider_id: &str,
    base_url: &str,
    model: Option<&str>,
    env_key: &str,
) -> String {
    let mut text = String::new();
    text.push_str(&format!(
        "# {CLI_MANAGER_CODEX_PROFILE_MARKER}. Do not put secrets in this file.\n"
    ));
    text.push_str(&format!(
        "# cc-switch provider id: {}\n\n",
        toml_basic_string(provider_id)
    ));
    if let Some(model) = model.filter(|value| !value.trim().is_empty()) {
        text.push_str(&format!("model = {}\n", toml_basic_string(model)));
    }
    text.push_str("model_provider = \"cli_manager\"\n\n");
    text.push_str("[model_providers.cli_manager]\n");
    text.push_str(&format!("name = {}\n", toml_basic_string(provider_name)));
    text.push_str(&format!("base_url = {}\n", toml_basic_string(base_url)));
    text.push_str(&format!("env_key = {}\n", toml_basic_string(env_key)));
    text
}

fn codex_runtime_from_provider(
    provider_id: String,
    provider_name: String,
    settings_config: String,
) -> Result<CodexProviderRuntimeConfig, String> {
    let parsed: Value = serde_json::from_str(&settings_config)
        .map_err(|_| "provider_config_invalid".to_string())?;
    let env = env_object(&parsed);
    let config_text = parsed.get("config").and_then(Value::as_str);
    let auth = parsed.get("auth").and_then(Value::as_object);
    let base_url = env
        .and_then(|env| {
            find_env_by_exact_or_suffix(
                env,
                &[
                    "OPENAI_BASE_URL",
                    "OPENAI_API_BASE",
                    "CODEX_BASE_URL",
                    "BASE_URL",
                    "API_BASE",
                    "ENDPOINT",
                ],
                &["_BASE_URL", "_API_BASE", "_ENDPOINT"],
            )
        })
        .or_else(|| {
            find_text_by_key_patterns(
                &parsed,
                &[
                    "openai_base_url",
                    "chatgpt_base_url",
                    "base_url",
                    "api_base",
                    "endpoint",
                    "url",
                ],
                &["_BASE_URL", "_API_BASE", "_ENDPOINT"],
            )
        })
        .or_else(|| {
            config_text.and_then(|config| {
                find_codex_toml_provider_base_url(config).or_else(|| {
                    find_toml_value_by_key_patterns(
                        config,
                        &[
                            "openai_base_url",
                            "chatgpt_base_url",
                            "base_url",
                            "api_base",
                            "endpoint",
                        ],
                        &["_BASE_URL", "_API_BASE", "_ENDPOINT"],
                    )
                })
            })
        })
        .ok_or_else(|| "provider_config_invalid: missing_codex_base_url".to_string())?;
    let model = env
        .and_then(|env| {
            find_env_by_exact_or_suffix(env, &["OPENAI_MODEL", "CODEX_MODEL", "MODEL"], &["_MODEL"])
        })
        .or_else(|| find_text_by_key_patterns(&parsed, &["model"], &["_MODEL"]))
        .or_else(|| {
            config_text
                .and_then(|config| find_toml_value_by_key_patterns(config, &["model"], &["_MODEL"]))
        });
    let wire_api = find_text_by_key_patterns(&parsed, &["wire_api"], &[])
        .or_else(|| config_text.and_then(|config| find_toml_value_by_key_patterns(config, &["wire_api"], &[])));
    let secret_value = env
        .and_then(find_codex_secret_value)
        .or_else(|| auth.and_then(find_codex_secret_value))
        .or_else(|| find_codex_secret_value_in_value(&parsed))
        .ok_or_else(|| "provider_config_invalid: missing_codex_api_key".to_string())?;
    let profile_name = codex_profile_name(&provider_id);
    let env_key = codex_secret_env_key(&provider_id);
    let profile_text = build_codex_profile_text(
        &provider_name,
        &provider_id,
        &base_url,
        model.as_deref(),
        &env_key,
    );
    Ok(CodexProviderRuntimeConfig {
        provider_id,
        provider_name,
        profile_name,
        env_key,
        secret_value,
        base_url,
        model,
        wire_api,
        profile_text,
    })
}

async fn load_codex_runtime_config(
    app: &tauri::AppHandle,
    provider_id: &str,
    db_path: Option<String>,
) -> Result<CodexProviderRuntimeConfig, String> {
    let path = resolve_db_path(app, db_path)?;
    let mut conn = open_db_readonly(&path).await?;
    let row = sqlx::query(
        "SELECT name, settings_config FROM providers WHERE id = ?1 AND app_type = 'codex'",
    )
    .bind(provider_id.trim())
    .fetch_optional(&mut conn)
    .await
    .map_err(|err| format!("db_query_failed: {err}"))?;
    let _ = conn.close().await;
    let row = row.ok_or_else(|| "provider_not_found".to_string())?;
    let name: String = row
        .try_get("name")
        .map_err(|err| format!("db_query_failed: {err}"))?;
    let settings_config: String = row
        .try_get("settings_config")
        .map_err(|err| format!("db_query_failed: {err}"))?;
    codex_runtime_from_provider(provider_id.trim().to_string(), name, settings_config)
}

fn resolve_codex_config_dir(
    app: &tauri::AppHandle,
    codex_config_dir: Option<String>,
) -> Result<PathBuf, String> {
    let _ = (app, codex_config_dir);
    app_paths::codex_providers_dir()
}

fn write_codex_profile(
    app: &tauri::AppHandle,
    codex_config_dir: Option<String>,
    runtime: &CodexProviderRuntimeConfig,
) -> Result<(), String> {
    let codex_dir = resolve_codex_config_dir(app, codex_config_dir)?;
    fs::create_dir_all(&codex_dir).map_err(|err| format!("profile_write_failed: {err}"))?;
    let profile_path = codex_dir.join(format!("{}.config.toml", runtime.profile_name));
    let tmp_path = codex_dir.join(format!("{}.config.toml.tmp", runtime.profile_name));
    fs::write(&tmp_path, &runtime.profile_text)
        .map_err(|err| format!("profile_write_failed: {err}"))?;
    replace_file_with_tmp(&tmp_path, &profile_path, "profile_write_failed")
}

fn replace_file_with_tmp(
    tmp_path: &Path,
    target_path: &Path,
    error_prefix: &str,
) -> Result<(), String> {
    if target_path.exists() {
        fs::remove_file(target_path).map_err(|err| format!("{error_prefix}: {err}"))?;
    }
    if let Err(err) = fs::rename(tmp_path, target_path) {
        let _ = fs::remove_file(tmp_path);
        return Err(format!("{error_prefix}: {err}"));
    }
    Ok(())
}

fn is_wsl_launch_shell(shell: Option<&str>) -> bool {
    if !cfg!(target_os = "windows") {
        return false;
    }
    matches!(
        shell.map(str::trim).map(str::to_ascii_lowercase).as_deref(),
        Some("wsl") | Some("bash")
    )
}

fn codex_home_for_shell(resolved_dir: &Path, shell: Option<&str>) -> String {
    let path = resolved_dir.to_string_lossy().into_owned();
    if is_wsl_launch_shell(shell) {
        return crate::wsl::windows_path_to_wsl(&path).unwrap_or(path);
    }
    path
}

fn is_cli_manager_codex_profile_candidate(path: &Path) -> bool {
    let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    file_name.starts_with("cli-manager-") && file_name.ends_with(".config.toml")
}

fn codex_profile_stem_from_path(path: &Path) -> Option<String> {
    let file_name = path.file_name()?.to_str()?;
    file_name.strip_prefix("cli-manager-")?;
    file_name
        .strip_suffix(".config.toml")
        .map(|_| file_name.trim_end_matches(".config.toml").to_string())
}

fn cleanup_codex_profiles_in_dir(
    codex_dir: &Path,
    keep_profile_names: &[String],
) -> Result<Vec<String>, String> {
    if !codex_dir.exists() {
        return Ok(Vec::new());
    }
    if !codex_dir.is_dir() {
        return Err("codex_config_dir_invalid".to_string());
    }

    let keep: std::collections::HashSet<String> = keep_profile_names
        .iter()
        .map(|name| name.trim())
        .filter(|name| !name.is_empty())
        .map(ToOwned::to_owned)
        .collect();
    let entries =
        fs::read_dir(codex_dir).map_err(|err| format!("profile_cleanup_failed: {err}"))?;
    let mut deleted = Vec::new();

    for entry in entries {
        let entry = entry.map_err(|err| format!("profile_cleanup_failed: {err}"))?;
        let path = entry.path();
        if !path.is_file() || !is_cli_manager_codex_profile_candidate(&path) {
            continue;
        }
        let Some(profile_name) = codex_profile_stem_from_path(&path) else {
            continue;
        };
        if keep.contains(&profile_name) {
            continue;
        }
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        if !text.contains(CLI_MANAGER_CODEX_PROFILE_MARKER) {
            continue;
        }
        fs::remove_file(&path).map_err(|err| format!("profile_cleanup_failed: {err}"))?;
        deleted.push(profile_name);
    }

    Ok(deleted)
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchCodexProfileCleanupResult {
    deleted_profile_names: Vec<String>,
}

#[tauri::command]
pub async fn ccswitch_cleanup_codex_profiles(
    app: tauri::AppHandle,
    keep_profile_names: Vec<String>,
    codex_config_dir: Option<String>,
) -> Result<CcSwitchCodexProfileCleanupResult, String> {
    let codex_dir = resolve_codex_config_dir(&app, codex_config_dir)?;
    let deleted_profile_names = cleanup_codex_profiles_in_dir(&codex_dir, &keep_profile_names)?;
    Ok(CcSwitchCodexProfileCleanupResult {
        deleted_profile_names,
    })
}

#[tauri::command]
pub async fn ccswitch_prepare_codex_provider(
    app: tauri::AppHandle,
    provider_id: String,
    db_path: Option<String>,
    codex_config_dir: Option<String>,
) -> Result<CcSwitchCodexProviderProfile, String> {
    let runtime = load_codex_runtime_config(&app, &provider_id, db_path).await?;
    write_codex_profile(&app, codex_config_dir, &runtime)?;
    Ok(CcSwitchCodexProviderProfile {
        provider_id: runtime.provider_id,
        provider_name: runtime.provider_name,
        profile_name: runtime.profile_name,
    })
}

pub(crate) async fn apply_codex_provider_launch_env(
    app: &tauri::AppHandle,
    launch_config: Option<CodexProviderLaunchConfig>,
    shell: Option<&str>,
    env_vars: &mut HashMap<String, String>,
) -> Result<(), String> {
    let Some(launch_config) = launch_config else {
        return Ok(());
    };
    let codex_config_dir = launch_config.codex_config_dir;
    let runtime =
        load_codex_runtime_config(app, &launch_config.provider_id, launch_config.db_path).await?;
    let resolved_dir = resolve_codex_config_dir(app, codex_config_dir.clone())?;
    env_vars.insert(
        "CODEX_HOME".to_string(),
        codex_home_for_shell(&resolved_dir, shell),
    );
    write_codex_profile(app, codex_config_dir, &runtime)?;
    env_vars.insert(runtime.env_key, runtime.secret_value);
    Ok(())
}

pub(crate) async fn refresh_claude_provider_launch_settings(
    app: &tauri::AppHandle,
    launch_config: Option<ClaudeProviderLaunchConfig>,
) -> Result<(), String> {
    let Some(launch_config) = launch_config else {
        return Ok(());
    };
    let project_id = launch_config.project_id.trim();
    if project_id.is_empty() {
        return Err("project_not_found".to_string());
    }
    let provider_id = launch_config.provider_id.trim();
    let (_provider_name, provider_env) =
        load_claude_provider_env(app, provider_id, launch_config.db_path).await?;
    write_claude_provider_settings(project_id, provider_id, &provider_env)?;
    Ok(())
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchProjectBadge {
    path: String,
    has_override: bool,
    provider_name: Option<String>,
    vendor_hint: Option<String>,
}

/// 纯函数：探测单个项目 settings.json 文本的供应商覆盖状态。
/// 文本缺失/损坏/env 无 ANTHROPIC_BASE_URL → (false, None)，单项容错不让整批失败；
/// 有覆盖但匹配不到供应商 → (true, None)（前端显示"自定义"）。
pub(crate) fn probe_settings_text(
    raw: Option<&str>,
    providers: &[(String, Map<String, Value>, Option<String>)],
) -> (bool, Option<String>, Option<String>) {
    let Some(raw) = raw else {
        return (false, None, None);
    };
    let parsed: Option<Value> = serde_json::from_str(raw).ok();
    let Some(project_env) = parsed.as_ref().and_then(env_object) else {
        return (false, None, None);
    };
    if env_text(project_env, "ANTHROPIC_BASE_URL").is_none() {
        return (false, None, None);
    }
    let matched_provider = providers
        .iter()
        .find(|(_, provider_env, _)| provider_matches_project_env(project_env, provider_env));
    let provider_name = matched_provider.map(|(name, _, _)| name.clone());
    let vendor_hint = matched_provider.and_then(|(_, _, vendor_hint)| vendor_hint.clone());
    (true, provider_name, vendor_hint)
}

#[tauri::command]
pub async fn ccswitch_probe_projects(
    app: tauri::AppHandle,
    project_paths: Vec<String>,
    db_path: Option<String>,
) -> Result<Vec<CcSwitchProjectBadge>, String> {
    let path = resolve_db_path(&app, db_path)?;
    let mut conn = open_db_readonly(&path).await?;
    let rows = sqlx::query(
        "SELECT name, settings_config FROM providers \
         WHERE app_type = 'claude' ORDER BY sort_index, name",
    )
    .fetch_all(&mut conn)
    .await
    .map_err(|err| format!("db_query_failed: {err}"))?;
    let _ = conn.close().await;

    let mut providers: Vec<(String, Map<String, Value>, Option<String>)> = Vec::new();
    for row in &rows {
        let map_err = |err: sqlx::Error| format!("db_query_failed: {err}");
        let name: String = row.try_get("name").map_err(map_err)?;
        let settings_config: String = row.try_get("settings_config").map_err(map_err)?;
        let parsed = parse_settings_config(&settings_config);
        let vendor_hint = parsed
            .as_ref()
            .and_then(|config| config.model.clone().or(config.base_url.clone()))
            .or_else(|| Some(name.clone()));
        let parsed_value: Option<Value> = serde_json::from_str(&settings_config).ok();
        if let Some(provider_env) = parsed_value.as_ref().and_then(env_object) {
            providers.push((name, provider_env.clone(), vendor_hint));
        }
    }

    let badges = project_paths
        .into_iter()
        .map(|project_path| {
            let settings_path = PathBuf::from(project_path.trim())
                .join(".claude")
                .join("settings.json");
            let raw = fs::read_to_string(&settings_path).ok();
            let (has_override, provider_name, vendor_hint) =
                probe_settings_text(raw.as_deref(), &providers);
            CcSwitchProjectBadge {
                path: project_path,
                has_override,
                provider_name,
                vendor_hint,
            }
        })
        .collect();

    Ok(badges)
}

// ---------- Phase 4: Common Config (from settings table) ----------

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchCommonConfig {
    app_type: String,
    config_json: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CcSwitchCommonConfigResponse {
    db_path: String,
    common_configs: Vec<CcSwitchCommonConfig>,
}

#[tauri::command]
pub async fn ccswitch_list_common_configs(
    app: tauri::AppHandle,
    db_path: Option<String>,
) -> Result<CcSwitchCommonConfigResponse, String> {
    let path = resolve_db_path(&app, db_path)?;
    let mut conn = open_db_readonly(&path).await?;

    // Error tolerance: check if settings table exists
    let table_exists =
        sqlx::query("SELECT name FROM sqlite_master WHERE type='table' AND name='settings'")
            .fetch_optional(&mut conn)
            .await
            .map_err(|err| format!("db_query_failed: {err}"))?
            .is_some();

    if !table_exists {
        let _ = conn.close().await;
        return Ok(CcSwitchCommonConfigResponse {
            db_path: path.to_string_lossy().into_owned(),
            common_configs: Vec::new(),
        });
    }

    // Query all common_config_* keys from settings table
    let rows = sqlx::query(
        "SELECT key, value FROM settings WHERE key LIKE 'common_config_%' ORDER BY key",
    )
    .fetch_all(&mut conn)
    .await
    .map_err(|err| format!("db_query_failed: {err}"))?;

    let common_configs = rows
        .iter()
        .filter_map(|row| {
            let key: Result<String, _> = row.try_get("key");
            let value: Result<String, _> = row.try_get("value");

            if let (Ok(key), Ok(value)) = (key, value) {
                // Extract app_type from key: "common_config_claude" -> "claude"
                if let Some(app_type) = key.strip_prefix("common_config_") {
                    return Some(CcSwitchCommonConfig {
                        app_type: app_type.to_string(),
                        config_json: value,
                    });
                }
            }
            None
        })
        .collect();

    let _ = conn.close().await;

    Ok(CcSwitchCommonConfigResponse {
        db_path: path.to_string_lossy().into_owned(),
        common_configs,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn secret_key_detection_matches_known_keys() {
        assert!(is_secret_env_key("ANTHROPIC_AUTH_TOKEN"));
        assert!(is_secret_env_key("ANTHROPIC_API_KEY"));
        assert!(is_secret_env_key("MY_SECRET"));
        assert!(!is_secret_env_key("ANTHROPIC_BASE_URL"));
        assert!(!is_secret_env_key("ANTHROPIC_MODEL"));
        assert!(!is_secret_env_key("ANTHROPIC_DEFAULT_HAIKU_MODEL"));
    }

    #[test]
    fn mask_secret_keeps_only_edges() {
        let masked = mask_secret("sk-abcdefghijklmnopqrstuvwxyz");
        assert_eq!(masked, "sk-a…wxyz");
        assert!(!masked.contains("bcdefghijklmnopqrstuv"));
        assert_eq!(mask_secret("short"), "***");
        assert_eq!(mask_secret(""), "***");
    }

    #[test]
    fn parse_settings_config_extracts_and_masks() {
        let raw = r#"{
            "env": {
                "ANTHROPIC_AUTH_TOKEN": "sk-1234567890abcdef",
                "ANTHROPIC_BASE_URL": "https://api.example.com",
                "ANTHROPIC_MODEL": "claude-fable-5"
            },
            "hooks": {}
        }"#;
        let parsed = parse_settings_config(raw).expect("config should parse");
        assert_eq!(parsed.base_url.as_deref(), Some("https://api.example.com"));
        assert_eq!(parsed.model.as_deref(), Some("claude-fable-5"));
        assert_eq!(
            parsed
                .masked_env
                .get("ANTHROPIC_AUTH_TOKEN")
                .map(String::as_str),
            Some("sk-1…cdef")
        );
        assert_eq!(
            parsed
                .masked_env
                .get("ANTHROPIC_BASE_URL")
                .map(String::as_str),
            Some("https://api.example.com")
        );
    }

    #[test]
    fn parse_settings_config_rejects_invalid_json() {
        assert!(parse_settings_config("not json").is_none());
    }

    #[test]
    fn summarize_model_error_prefers_json_code_and_message() {
        let body = r#"{"error":{"code":"model_not_found","message":"The model claude-opus-4-8 does not exist or you do not have access to it."}}"#;
        assert_eq!(
            summarize_model_error(404, body),
            "HTTP 404: model_not_found - The model claude-opus-4-8 does not exist or you do not have access to it."
        );
    }

    #[test]
    fn summarize_model_error_shortens_jsonish_gateway_noise() {
        let body = r#"('"error""code"model not found","mesage"."No available channel for model claude-opus-4-8 undergroup ClaudeCode (distributor (request id: 202607030736423540690538268d9d6wNSqzoMo),"type": new api error')"#;
        assert_eq!(
            summarize_model_error(503, body),
            "HTTP 503: model not found - No channel for model claude-opus-4-8"
        );
    }

    fn obj(json: &str) -> Map<String, Value> {
        serde_json::from_str::<Value>(json)
            .expect("test json should parse")
            .as_object()
            .expect("test json should be an object")
            .clone()
    }

    #[test]
    fn replace_anthropic_env_clears_legacy_and_keeps_user_keys() {
        let mut settings = obj(r#"{
                "env": {
                    "ANTHROPIC_BASE_URL": "https://old.example.com",
                    "ANTHROPIC_AUTH_TOKEN": "sk-old",
                    "ANTHROPIC_SMALL_FAST_MODEL": "old-haiku",
                    "HTTP_PROXY": "http://127.0.0.1:7890"
                }
            }"#);
        let provider_env = obj(r#"{
                "ANTHROPIC_BASE_URL": "https://new.example.com",
                "ANTHROPIC_API_KEY": "sk-new"
            }"#);
        replace_anthropic_env(&mut settings, &provider_env);
        let env = settings.get("env").unwrap().as_object().unwrap();
        assert_eq!(
            env.get("ANTHROPIC_BASE_URL").and_then(Value::as_str),
            Some("https://new.example.com")
        );
        assert_eq!(
            env.get("ANTHROPIC_API_KEY").and_then(Value::as_str),
            Some("sk-new")
        );
        // 上一家供应商遗留的 ANTHROPIC_ key 必须被清掉
        assert!(env.get("ANTHROPIC_AUTH_TOKEN").is_none());
        assert!(env.get("ANTHROPIC_SMALL_FAST_MODEL").is_none());
        // 用户自有非 ANTHROPIC_ key 保留
        assert_eq!(
            env.get("HTTP_PROXY").and_then(Value::as_str),
            Some("http://127.0.0.1:7890")
        );
    }

    #[test]
    fn replace_anthropic_env_keeps_other_top_level_fields() {
        let mut settings = obj(r#"{
                "env": {"ANTHROPIC_AUTH_TOKEN": "sk-old"},
                "hooks": {"UserPromptSubmit": [{"matcher": "*"}]},
                "permissions": {"allow": ["Bash"]},
                "skipDangerousModePermissionPrompt": true
            }"#);
        let hooks_before = settings.get("hooks").cloned();
        let permissions_before = settings.get("permissions").cloned();
        let provider_env = obj(r#"{"ANTHROPIC_BASE_URL": "https://new.example.com"}"#);
        replace_anthropic_env(&mut settings, &provider_env);
        assert_eq!(settings.get("hooks").cloned(), hooks_before);
        assert_eq!(settings.get("permissions").cloned(), permissions_before);
        assert_eq!(
            settings.get("skipDangerousModePermissionPrompt"),
            Some(&Value::Bool(true))
        );
    }

    #[test]
    fn replace_anthropic_env_creates_env_when_missing_or_invalid() {
        let provider_env = obj(r#"{"ANTHROPIC_BASE_URL": "https://new.example.com"}"#);

        let mut without_env = Map::new();
        replace_anthropic_env(&mut without_env, &provider_env);
        let env = without_env.get("env").unwrap().as_object().unwrap();
        assert_eq!(
            env.get("ANTHROPIC_BASE_URL").and_then(Value::as_str),
            Some("https://new.example.com")
        );

        let mut invalid_env = obj(r#"{"env": "not an object"}"#);
        replace_anthropic_env(&mut invalid_env, &provider_env);
        let env = invalid_env.get("env").unwrap().as_object().unwrap();
        assert_eq!(env.len(), 1);
        assert_eq!(
            env.get("ANTHROPIC_BASE_URL").and_then(Value::as_str),
            Some("https://new.example.com")
        );
    }

    #[test]
    fn merge_settings_text_rejects_corrupted_json() {
        let provider_env = obj(r#"{"ANTHROPIC_BASE_URL": "https://new.example.com"}"#);
        assert_eq!(
            merge_settings_text(Some("{ not json"), &provider_env),
            Err("settings_parse_failed".to_string())
        );
        // 合法 JSON 但顶层不是对象，同样视为解析失败
        assert_eq!(
            merge_settings_text(Some("[1, 2]"), &provider_env),
            Err("settings_parse_failed".to_string())
        );
    }

    #[test]
    fn merge_settings_text_handles_missing_file() {
        let provider_env = obj(
            r#"{"ANTHROPIC_BASE_URL": "https://new.example.com", "ANTHROPIC_AUTH_TOKEN": "sk-new"}"#,
        );
        let text = merge_settings_text(None, &provider_env).unwrap();
        let value: Value = serde_json::from_str(&text).unwrap();
        assert_eq!(
            value["env"]["ANTHROPIC_BASE_URL"].as_str(),
            Some("https://new.example.com")
        );
        assert_eq!(
            value["env"]["ANTHROPIC_AUTH_TOKEN"].as_str(),
            Some("sk-new")
        );
    }

    #[test]
    fn provider_match_requires_base_url_and_token() {
        let provider =
            obj(r#"{"ANTHROPIC_BASE_URL": "https://a.com", "ANTHROPIC_AUTH_TOKEN": "sk-1"}"#);

        let by_auth_token =
            obj(r#"{"ANTHROPIC_BASE_URL": "https://a.com", "ANTHROPIC_AUTH_TOKEN": "sk-1"}"#);
        assert!(provider_matches_project_env(&by_auth_token, &provider));

        let wrong_base =
            obj(r#"{"ANTHROPIC_BASE_URL": "https://b.com", "ANTHROPIC_AUTH_TOKEN": "sk-1"}"#);
        assert!(!provider_matches_project_env(&wrong_base, &provider));

        let missing_token = obj(r#"{"ANTHROPIC_BASE_URL": "https://a.com"}"#);
        assert!(!provider_matches_project_env(&missing_token, &provider));

        let provider_with_api_key =
            obj(r#"{"ANTHROPIC_BASE_URL": "https://a.com", "ANTHROPIC_API_KEY": "sk-2"}"#);
        let by_api_key =
            obj(r#"{"ANTHROPIC_BASE_URL": "https://a.com", "ANTHROPIC_API_KEY": "sk-2"}"#);
        assert!(provider_matches_project_env(
            &by_api_key,
            &provider_with_api_key
        ));
    }

    // ---------- Phase 3 ----------

    #[test]
    fn strip_env_section_removes_env_and_keeps_other_fields() {
        let raw = r#"{
            "env": {
                "ANTHROPIC_BASE_URL": "https://a.com",
                "ANTHROPIC_AUTH_TOKEN": "sk-1",
                "HTTP_PROXY": "http://127.0.0.1:7890"
            },
            "hooks": {"UserPromptSubmit": [{"matcher": "*"}]},
            "permissions": {"allow": ["Bash"]}
        }"#;
        let text = strip_env_section(raw).unwrap().expect("should keep file");
        let value: Value = serde_json::from_str(&text).unwrap();
        // env 整段删除（含用户自有非 ANTHROPIC_ key）
        assert!(value.get("env").is_none());
        // 其余顶层字段原样保留
        assert!(value.get("hooks").is_some());
        assert!(value.get("permissions").is_some());
    }

    #[test]
    fn strip_env_section_signals_file_deletion_when_empty() {
        // 只剩 env → 删除后顶层为空 → None 表示应删除文件
        let only_env = r#"{"env": {"ANTHROPIC_BASE_URL": "https://a.com"}}"#;
        assert_eq!(strip_env_section(only_env), Ok(None));
        // 本来就是空对象 → 同样应删除文件
        assert_eq!(strip_env_section("{}"), Ok(None));
    }

    #[test]
    fn strip_env_section_rejects_corrupted_json() {
        assert_eq!(
            strip_env_section("{ not json"),
            Err("settings_parse_failed".to_string())
        );
        // 合法 JSON 但顶层非对象，同样视为解析失败
        assert_eq!(
            strip_env_section("[1, 2]"),
            Err("settings_parse_failed".to_string())
        );
    }

    #[test]
    fn reset_settings_file_is_noop_when_file_missing() {
        let dir = std::env::temp_dir().join(format!(
            "ccswitch-reset-noop-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        fs::create_dir_all(&dir).unwrap();
        // settings.json 不存在（连 .claude 都没有）→ no-op 成功
        assert_eq!(reset_settings_file(&dir), Ok(()));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn replace_file_with_tmp_overwrites_existing_target() {
        let tmp = tempfile::tempdir().unwrap();
        let target_path = tmp.path().join("settings.json");
        let tmp_path = tmp.path().join("settings.json.tmp");
        fs::write(&target_path, "old").unwrap();
        fs::write(&tmp_path, "new").unwrap();

        replace_file_with_tmp(&tmp_path, &target_path, "settings_write_failed").unwrap();

        assert_eq!(fs::read_to_string(&target_path).unwrap(), "new");
        assert!(!tmp_path.exists());
    }

    #[test]
    #[cfg(target_os = "windows")]
    fn codex_home_for_shell_uses_wsl_path_for_wsl_shell() {
        let path = Path::new(r"C:\Users\Administrator\.cli-manager\providers\codex");
        assert_eq!(
            codex_home_for_shell(path, Some("wsl")),
            "/mnt/c/Users/Administrator/.cli-manager/providers/codex"
        );
        assert_eq!(
            codex_home_for_shell(path, Some("bash")),
            "/mnt/c/Users/Administrator/.cli-manager/providers/codex"
        );
        assert_eq!(
            codex_home_for_shell(path, Some("powershell")),
            r"C:\Users\Administrator\.cli-manager\providers\codex"
        );
    }

    #[test]
    fn anthropic_env_keys_extracts_only_prefixed_key_names() {
        let raw = r#"{
            "env": {
                "ANTHROPIC_BASE_URL": "https://a.com",
                "ANTHROPIC_AUTH_TOKEN": "sk-secret",
                "HTTP_PROXY": "http://127.0.0.1:7890"
            }
        }"#;
        let keys = anthropic_env_keys(raw);
        assert!(keys.contains(&"ANTHROPIC_BASE_URL".to_string()));
        assert!(keys.contains(&"ANTHROPIC_AUTH_TOKEN".to_string()));
        assert!(!keys.contains(&"HTTP_PROXY".to_string()));
        // 只返回 key 名，不含任何值
        assert!(!keys.iter().any(|k| k.contains("sk-secret")));

        // 损坏 JSON / 无 env → 空数组容错
        assert!(anthropic_env_keys("{ not json").is_empty());
        assert!(anthropic_env_keys(r#"{"hooks": {}}"#).is_empty());
    }

    #[test]
    fn codex_runtime_profile_uses_generated_env_key_without_secret() {
        let runtime = codex_runtime_from_provider(
            "Provider/One".to_string(),
            "Proxy \"One\"".to_string(),
            r#"{
                "env": {
                    "OPENAI_BASE_URL": "https://proxy.example.com/v1",
                    "OPENAI_API_KEY": "sk-secret-value",
                    "OPENAI_MODEL": "gpt-5.4"
                }
            }"#
            .to_string(),
        )
        .expect("codex config should parse");

        assert!(runtime
            .profile_name
            .starts_with("cli-manager-provider-one-"));
        assert!(runtime.env_key.starts_with("CLI_MANAGER_CODEX_PROVIDER_"));
        assert_eq!(runtime.secret_value, "sk-secret-value");
        assert!(runtime.profile_text.contains("model = \"gpt-5.4\""));
        assert!(runtime
            .profile_text
            .contains("model_provider = \"cli_manager\""));
        assert!(runtime
            .profile_text
            .contains("base_url = \"https://proxy.example.com/v1\""));
        assert!(runtime
            .profile_text
            .contains(&format!("env_key = \"{}\"", runtime.env_key)));
        assert!(!runtime.profile_text.contains("sk-secret-value"));
    }

    #[test]
    fn codex_runtime_rejects_missing_base_or_secret() {
        assert_eq!(
            codex_runtime_from_provider(
                "p".to_string(),
                "Provider".to_string(),
                r#"{"env":{"OPENAI_API_KEY":"sk"}}"#.to_string(),
            )
            .map(|_| ()),
            Err("provider_config_invalid: missing_codex_base_url".to_string())
        );
        assert_eq!(
            codex_runtime_from_provider(
                "p".to_string(),
                "Provider".to_string(),
                r#"{"env":{"OPENAI_BASE_URL":"https://example.com"}}"#.to_string(),
            )
            .map(|_| ()),
            Err("provider_config_invalid: missing_codex_api_key".to_string())
        );
    }

    #[test]
    fn codex_runtime_accepts_codex_config_style_provider_shape() {
        let runtime = codex_runtime_from_provider(
            "codex-provider".to_string(),
            "Codex Proxy".to_string(),
            r#"{
                "model": "gpt-5.4",
                "model_provider": "proxy",
                "model_providers": {
                    "proxy": {
                        "name": "OpenAI using proxy",
                        "base_url": "https://proxy.example.com/v1",
                        "env_key": "OPENAI_API_KEY"
                    }
                },
                "env": {
                    "OPENAI_API_KEY": "sk-codex-secret"
                }
            }"#
            .to_string(),
        )
        .expect("codex config-style provider should parse");

        assert!(runtime
            .profile_text
            .contains("base_url = \"https://proxy.example.com/v1\""));
        assert!(runtime.profile_text.contains("model = \"gpt-5.4\""));
        assert!(!runtime.profile_text.contains("sk-codex-secret"));
        assert_eq!(runtime.secret_value, "sk-codex-secret");
    }

    #[test]
    fn codex_runtime_accepts_non_env_secret_and_lowercase_base_keys() {
        let runtime = codex_runtime_from_provider(
            "codex-provider".to_string(),
            "Codex Proxy".to_string(),
            r#"{
                "openai-base-url": "https://openai-compatible.example.com/v1",
                "api-key": "sk-non-env-secret"
            }"#
            .to_string(),
        )
        .expect("non-env cc-switch codex shape should parse");

        assert!(runtime
            .profile_text
            .contains("base_url = \"https://openai-compatible.example.com/v1\""));
        assert!(!runtime.profile_text.contains("sk-non-env-secret"));
        assert_eq!(runtime.secret_value, "sk-non-env-secret");
    }

    #[test]
    fn codex_runtime_accepts_ccswitch_auth_and_config_toml_shape() {
        let runtime = codex_runtime_from_provider(
            "codex-provider".to_string(),
            "Codex Proxy".to_string(),
            serde_json::json!({
                "auth": { "OPENAI_API_KEY": "sk-auth-secret" },
                "config": "model_provider = \"custom\"\nmodel = \"gpt-5.5\"\n\n[model_providers.custom]\nname = \"custom\"\nbase_url = \"https://toml-proxy.example.com/v1\"\nwire_api = \"responses\"\n"
            })
            .to_string(),
        )
        .expect("cc-switch auth + TOML config shape should parse");

        assert!(runtime
            .profile_text
            .contains("base_url = \"https://toml-proxy.example.com/v1\""));
        assert!(runtime.profile_text.contains("model = \"gpt-5.5\""));
        assert!(!runtime.profile_text.contains("sk-auth-secret"));
        assert_eq!(runtime.secret_value, "sk-auth-secret");
    }

    #[test]
    fn cleanup_codex_profiles_deletes_only_unreferenced_cli_manager_files() {
        let tmp = tempfile::tempdir().unwrap();
        let keep_path = tmp.path().join("cli-manager-keep.config.toml");
        let unused_path = tmp.path().join("cli-manager-unused.config.toml");
        let unmanaged_path = tmp.path().join("cli-manager-unmanaged.config.toml");
        let user_path = tmp.path().join("user-profile.config.toml");

        fs::write(
            &keep_path,
            format!("# {CLI_MANAGER_CODEX_PROFILE_MARKER}\nmodel = \"gpt-5\"\n"),
        )
        .unwrap();
        fs::write(
            &unused_path,
            format!("# {CLI_MANAGER_CODEX_PROFILE_MARKER}\nmodel = \"gpt-5\"\n"),
        )
        .unwrap();
        fs::write(&unmanaged_path, "model = \"user-owned\"\n").unwrap();
        fs::write(&user_path, "model = \"user-owned\"\n").unwrap();

        let deleted =
            cleanup_codex_profiles_in_dir(tmp.path(), &["cli-manager-keep".to_string()]).unwrap();

        assert_eq!(deleted, vec!["cli-manager-unused".to_string()]);
        assert!(keep_path.is_file());
        assert!(!unused_path.exists());
        assert!(unmanaged_path.is_file());
        assert!(user_path.is_file());
    }

    #[test]
    fn probe_settings_text_tolerates_missing_and_corrupted() {
        let providers = vec![(
            "ProviderA".to_string(),
            obj(r#"{"ANTHROPIC_BASE_URL": "https://a.com", "ANTHROPIC_AUTH_TOKEN": "sk-1"}"#),
            Some("claude".to_string()),
        )];

        // 文件缺失 / 损坏 JSON / 无 env → hasOverride=false，不让整批失败
        assert_eq!(probe_settings_text(None, &providers), (false, None, None));
        assert_eq!(
            probe_settings_text(Some("{ not json"), &providers),
            (false, None, None)
        );
        assert_eq!(
            probe_settings_text(Some(r#"{"hooks": {}}"#), &providers),
            (false, None, None)
        );

        // 匹配到供应商 → 返回名字
        let matched =
            r#"{"env": {"ANTHROPIC_BASE_URL": "https://a.com", "ANTHROPIC_AUTH_TOKEN": "sk-1"}}"#;
        assert_eq!(
            probe_settings_text(Some(matched), &providers),
            (
                true,
                Some("ProviderA".to_string()),
                Some("claude".to_string())
            )
        );

        // 有覆盖但匹配不到 → (true, None)，前端显示"自定义"
        let custom = r#"{"env": {"ANTHROPIC_BASE_URL": "https://other.com", "ANTHROPIC_AUTH_TOKEN": "sk-x"}}"#;
        assert_eq!(
            probe_settings_text(Some(custom), &providers),
            (true, None, None)
        );
    }
}
